### ISSUE TITLE
`link_flair_text` is sometimes missing 

### ISSUE THREAD

**Issue by sunny-lan** [pushshift/api#17]
For example: https://api.pushshift.io/reddit/search/submission?subreddit=science&q=engineers
Look for post with id `98o0wk`

Here is the actual post:  https://www.reddit.com/r/science/comments/98j5bn/engineers_create_most_wearresistant_metal_alloy/

The `Engineering` flair is missing

**Comment by pushshift** [comment]
This was due to a Reddit API error where flairs were missing for a while.  This should be resolved for current data.

**Comment by pacal** [comment]
I noticed that this is still happening. In this case posts from /hardwareswap many are missing the link_flair_text. It shows up in the actual post.json from reddit.

**Comment by pushshift** [comment]
This was actually an issue with Reddit's API earlier in the year where flairs were not showing up correctly for submissions (and I believe comments were affected at some point as well).

Do you know approximately what time frame these flairs are missing?  I may need to re-ingest at some point to get accurate data for flairs (The missing flair issue was ongoing for a couple months from Reddit's API)

If you have the month or general time range that appear to be affected, I'll investigate further.

Thanks!

**Comment by pacal** [comment]
Current data set as of now. 
requests.get("https://api.pushshift.io/reddit/submission/search/?subreddit=hardwareswap&limit=500")

Only a small set show up with the link_flair. As stated earlier is present in the direct reddit .json data if I pull that.

thanks

**Comment by pxue** [comment]
Are there anyway to filter by link_flair_text? using `q=flair:xxx` does not seem to return expected result

**Comment by phxvyper** [comment]
This issue seems to be persistent with new posts. This query, for example, returns many recent posts that have flairs but aren't showing up in `link_flair_text`:

https://api.pushshift.io/reddit/submission/search?sort=desc&sort_type=created_utc&subreddit=sbubby&size=1000
